Adding blueprint
GenesysCloudBlueprints/partial-transcription-blueprint pull request #1
Opened 2022-01-12 20:33 UTC by diemenschmaschine92

Adding the complete partial transcription blueprint

2022-01-14 15:06 UTC, timsmithgenesys requested changes

2022-01-14 15:06 UTC, timsmithgenesys commented on blueprint/index.md
> +image: images/5.png
There's no image by this name included in the PR

2022-01-14 15:06 UTC, timsmithgenesys commented on blueprint/index.md
> +- **Genesys AppFoundry** - The Genesys app marketplace for solutions that run on the Genesys Cloud platform. You download the integration used in this solution from the Genesys AppFoundry.
Add a link to the integration here

2022-01-14 15:06 UTC, timsmithgenesys commented on blueprint/index.md
> +- **Platform API Javascript Client** - The sample app employs React+Typescript, thus the javascript SDK is used here. However, the same functionality could be achieved using other languages. Find the
The link and URL is redundant

2022-01-14 15:06 UTC, timsmithgenesys commented on blueprint/index.md
> +- **Platform API Javascript Client** - The sample app employs React+Typescript, thus the javascript SDK is used here. However, the same functionality could be achieved using other languages. Find the
TypeScript should always be spelled as one word with a capital T and S. There are 4 instances of the word in this document

2022-01-14 15:06 UTC, timsmithgenesys commented on blueprint/index.md
> +* [Genesys Cloud Platform SDK - Javascript](https://developer.genesys.cloud/api/rest/client-libraries/javascript/)
Drop the domain from links to the dev center, just use the path

2022-01-14 15:06 UTC, timsmithgenesys commented on blueprint/index.md
> +1. Select a queue that you are a member of. Note that setting up a test queue with only yourself as a member is a quick solution here, since this guarantees that inbound calls to the queue will be as
This should say "Select a queue that you are a member of _and are activated in_." to remind people to check their activation status in the queue if they aren't getting things assigned.

2022-01-14 15:06 UTC, timsmithgenesys commented on blueprint/index.md
> +The `genesysCloudUtils` file contains the intermediate functions that in turn call Genesys Cloud SDK methods. These functions return promises that are handled upon resolution in the file and in the i
include the file extension and relative path in the repo when referencing a specific file (`genesysCloudUtils`)

2022-01-14 15:06 UTC, timsmithgenesys commented on public/index.html
> +    <title>React App</title>
Set a title for the app

2022-01-14 15:06 UTC, timsmithgenesys commented on public/manifest.json
> +  "short_name": "React App",
set short_name and name and remove the icon references you aren't using in the project

2022-01-14 15:06 UTC, timsmithgenesys commented on src/App.css
> +  font-family: "Roboto",sans-serif;
Are you importing the roboto font from somewhere? I don't see the font import. If you haven't, you can generate a link with the styles you need here: https://fonts.google.com/?query=roboto or grab the link from the index.html file for the dev center.

2022-01-14 15:06 UTC, timsmithgenesys commented on src/components/accordion/Accordion.tsx
> +	heading: React.ReactNode;
indentation

2022-01-14 15:06 UTC, timsmithgenesys commented on src/components/accordion/Accordion.tsx
> +export function Accordion(props: IAccordionProps) {
You can replace this component with the genesys-react-components library if you like. Not required. https://www.npmjs.com/package/genesys-react-components

2022-01-14 15:06 UTC, timsmithgenesys commented on src/logo.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 841.9 595.3"><g fill="#61DAFB"><path d="M666.3 296.5c0-32.5-40.7-63.3-103.1-82.4 14.4-63.6 8-114.2-20.2-130.4-6.5-3.8-14.1-5.6-22.4-5.6v22.3c4.6 0
this file can be removed (default react "logo")

2022-01-14 15:06 UTC, timsmithgenesys commented on src/utils/genesysCloudUtils.ts
> +// const conversationsApi = new platformClient.ConversationsApi();
remove commented out code

2022-01-14 15:06 UTC, timsmithgenesys commented on src/utils/genesysCloudUtils.ts
> +export function authenticate() {
This file, specifically,  should be heavily commented. State the purpose of every function and explain every Genesys Cloud API request (briefly). This is the part of the app that people are going to reference to learn how to use our APIs, so being thorough with commenting will help guide people through it.

2022-01-14 15:07 UTC, timsmithgenesys commented
Consider publishing this page using github pages so there's a live demo of it available. Publishing the app is super easy using the [gh-pages](https://www.npmjs.com/package/gh-pages) package. Let me know if you need me to turn github pages on for the repo or have any questions; not sure if you have permissions to do that.

2022-01-25 16:06 UTC, timsmithgenesys approved these changes

2022-01-31 14:48 UTC, timsmithgenesys commented
![approve](https://user-images.githubusercontent.com/74417894/151814789-8ff863c3-4720-462a-baea-d7095bf5802a.png)

2022-02-24 13:52 UTC, carnellj approved these changes

2022-02-24 13:52 UTC, carnellj approved these changes

2022-02-24 13:53 UTC, merged